### ISSUE TITLE
Add methods for tracking component order

### ISSUE THREAD

**Issue by bradenpecora** [UT-Computational-NE/FlowForge#31]
## Acceptance Criteria

- [ ] Criterion 1
- [ ] Criterion 2
- [ ] Criterion 3

## Definition of Done

- [ ] All acceptance criteria are met
- [ ] Task has been reviewed and approved by a supervisor/team lead
- [ ] Any necessary documentation has been completed
- [ ] Task outcomes have been tested and verified

## Dependencies

- Dependency 1
- Dependency 2
